version: '3.8'
services:
  postgres:
    image: ankane/pgvector
    container_name: bi_pgvector
    environment:
      POSTGRES_USER: biuser
      POSTGRES_PASSWORD: bipassword
      POSTGRES_DB: bidb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 